### ISSUE TITLE
Public repo

### ISSUE THREAD

**Issue by Jukelyn** [SatsaraWasTaken/MIT-homeworks#1]
Hello, unsure if you mean for this to be a public repo or not but just as a reminder, this is public. I see you're doing something related to a class, if you don't want this to be shared, be sure to private the repo from the repo settings. Cheers and good luck learning Python!

**Comment by SatsaraWasTaken** [comment]
Thank you for the reminder and your kind wishes! I thought it would be helpful to post it publicly so that other newcomers like me can better understand the process. While I'm not very familiar with how public Git is, I hope it won't be an issue. If anyone finds it bothersome, they can simply choose to ignore it. Wishing you a wonderful rest of the week!

**Comment by SatsaraWasTaken** [comment]
> Hello, unsure if you mean for this to be a public repo or not but just as a reminder, this is public. I see you're doing something related to a class, if you don't want this to be shared, be sure to private the repo from the repo settings. Cheers and good luck learning Python!

Thank you for the reminder and your kind wishes! I thought it would be helpful to post it publicly so that other newcomers like me can better understand the process. While I'm not very familiar with how public Git is, I hope it won't be an issue. If anyone finds it bothersome, they can simply choose to ignore it. Wishing you a wonderful rest of the week!

**Comment by Jukelyn** [comment]
Ah, I see. That's fair, I think that's a good idea as long as you were aware. I didn't know if it was the case that you had it be public when in reality the code or other stuff isn't supposed to view outside of the class/school.
